# Generated by Django 5.2 on 2025-06-13 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_admission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
